### ISSUE TITLE
In new project dialog, broken links (404) for documentation on DragonBones, Box2D, and SWF features

### ISSUE THREAD

**Issue by travisfw** [korlibs/korge-intellij-plugin#28]
![Screenshot from 2020-08-07 05-28-05](https://user-images.githubusercontent.com/655987/89645646-0f6d1d00-d86f-11ea-8330-90078039ba6b.png)

**Comment by christianitis** [comment]
Happens to me too.

**Comment by soywiz** [comment]
Yeah, now documentation is in a different domain. 

https://korlibs.soywiz.com/
->
https://docs.korge.org/

As a temporal workaround you can change the domain manually.

**Comment by soywiz** [comment]
I believe this was fixed already
