### ISSUE TITLE
Ktree files doesn't work on macos

### ISSUE THREAD

**Issue by valiknet18** [korlibs/korge-intellij-plugin#35]
I'm try to open ktree file in intellij 2021.1.3 (i'm also tried on 2021.2.0 and 2021.2.3), and this file doesn't work as expected cause i'm have an error 

`java.lang.UnsatisfiedLinkError: Error looking up function 'CVDisplayLinkCreateWithCGDisplay': dlsym(0xfff129e253e0, CVDisplayLinkCreateWithCGDisplay): symbol not found`

I'm using macos 12.0.1

**Comment by soywiz** [comment]
Closing since latest intellij plugin don't include this, and the next version is likely to use HTML for the editors.
