### ISSUE TITLE
"Korge" no longer appears as an option in the project setup window

### ISSUE THREAD

**Issue by Kietyo** [korlibs/korge-intellij-plugin#39]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/5054996/164967741-26878ee7-fc3c-463a-bed1-364b8ffe27b2.png">

Note that this is on the latest version of intellij: 2022.1

Before I updated the IDE, Korge used to be available as an option. They may've changed something about the project setup wizard so the plugin might need updating.

**Comment by soywiz** [comment]
@Kietyo have you updated korge plugin to 2.7.0?
https://plugins.jetbrains.com/plugin/9676-korge/versions/stable/169144

**Comment by Kietyo** [comment]
Oh I was on an older version. Updating it fixed it. Thanks!
