### ISSUE TITLE
build.gradle.kts libs

### ISSUE THREAD

**Issue by monyettenyom** [korlibs/korge-intellij-plugin#43]
Hallo, I created a Korge project on IntelliJ 2022.1. In the file build.gradle.kts IntelliJ won't recognised plugins "libs". 

![Bildschirmfoto 2022-08-25 um 13 12 18](https://user-images.githubusercontent.com/58295352/186652343-38be3a0b-39aa-48e2-a017-62d21e395d69.png)
Is there any alternative to do otherwise? I've tried this one: 

apply"<"KorgeGradlePlugin">"()

korge {
	id = "com.soywiz.samples.animations"
	targetDefault()
}

but the error code showed: unsolved reference KorgeGradlePlugin. 

I've tried also other method, but the error Message showed me: unsolved reference: soywiz.

Thanks and look forward to your advice

**Comment by soywiz** [comment]
You can also use:

```kotlin
plugins {
  id("com.soywiz.korge") version "3.0.0"
}
``` 

The libs error is actually a editor error but it works properly.
