### ISSUE TITLE
Feature Request: Add ability to automatically add -sources.jar file for locally built Korge version that's published to mavenLocal.

### ISSUE THREAD

**Issue by Kietyo** [korlibs/korge-intellij-plugin#44]
Context: https://youtrack.jetbrains.com/issue/KTIJ-22551/MPP-Navigation-Decompiled-code-instead-of-sources-for-locally-published-MPP-library#focus=Comments-27-6415699.0-0

Example of someone who's done this before: https://youtrack.jetbrains.com/issue/IDEA-227215/Maven-local-repo-sources-not-imported-in-Idea-libraries-after-Gradle-6-update#focus=Comments-27-6412991.0-0

**Comment by Kietyo** [comment]
Plugin documentation: https://plugins.jetbrains.com/docs/intellij/welcome.html#receiving-notification-about-project-closeopen-events

**Comment by soywiz** [comment]
Thanks for the details! Let's see if we can do something. In any case if we manage to use the plugin to fix this, would be nice to also make a PR to fix it in IDEA itself

**Comment by Kietyo** [comment]
Abe (the person who created a plugin to fix this issue themselves) generously shared their code:

https://youtrack.jetbrains.com/issue/IDEA-227215/Maven-local-repo-sources-not-imported-in-Idea-libraries-after-Gradle-6-update#focus=Comments-27-6417980.0-0

https://gist.github.com/hamoid/2438191187526e1c5dabced31bba9b38

**Comment by Kietyo** [comment]
I don't seem to have permissions to assign this issue to myself.

Feel free to assign to me, I can try taking this on.

**Comment by hamoid** [comment]
If there are questions I can try to answer :-) I hope the comments I added to the code help a bit.

**Comment by Kietyo** [comment]
Thanks Abe, it was very useful. Here's the solution I came up with:

https://github.com/korlibs/korge-intellij-plugin/pull/45

**Comment by soywiz** [comment]
This was already merged and available in the intellij plugin
