### ISSUE TITLE
Particles editor

### ISSUE THREAD

**Issue by soywiz** [korlibs/korge-intellij-plugin#6]

**Comment by RezMike** [comment]
What functions should Particles editor have? Maybe there is an example?

**Comment by soywiz** [comment]
Sliders to adjust the values in .pex files and a previsualization. We might need to include a korge view to do this. With korui was possible to include korge in AWT. This might require enabling that possibility again. (Or rendering particles via software)

* https://github.com/korlibs/korge-intellij-plugin/blob/master/src/main/kotlin/com/soywiz/korge/intellij/completion/PexCompletionContributor.kt
* https://github.com/korlibs/korge-samples/blob/8ef957b086bf218aad13859d0f08aa10b3cae52d/particles/src/commonMain/resources/particle/particle.pex

**Comment by soywiz** [comment]
This ParticleEmitter class just does the simulation: https://github.com/korlibs/korge/blob/master/korge/src/commonMain/kotlin/com/soywiz/korge/particle/ParticleEmitter.kt#L19 no need for a korge view.

Here is how korge converts that simulation into its rendering:
https://github.com/korlibs/korge/blob/64563e41ac104155c52d75320ca568a8a7b1a218/korge/src/commonMain/kotlin/com/soywiz/korge/particle/ParticleEmitterView.kt#L47-L51

We might just do plain rendering using AWT and using the simulator. And add sliders to adjust the values.

Feel brave enough to do that? Need help with setting the UI?

**Comment by RezMike** [comment]
I think I first need to finish work with tiledmap editor. I just wanted to know how hard this issue is.
